### ISSUE TITLE
Using with request-promise

### ISSUE THREAD

**Issue by itaysk** [demmer/bluebird-retry#32]
I have this very simple test:
server which always returns 503 (and log the request). Therefore request-promise will reject.
client which should continuously request the server.

I expect the client to hit the server 5 times and then reject. In reality the client hits the serve 1 time, then reject.

Server:

    var http = require('http');
    var server = http.createServer(function (req, res) {
        console.log(new Date());
        res.statusCode = 503;
        res.end();
    });
    server.listen(8000);

Client:

    var rp = require('request-promise');
    var retry = require('bluebird-retry');
    retry(rp('http://localhost:8000').promise(), { max_tries: 5 })
        .then(function (res) {
            console.log('success');
        })
        .catch(function (err) {
            console.log('fail');
        });

Am I doing something wrong?

**Comment by demmer** [comment]
The problem is that you need to wrap your call to `rp` in a function like this:

```
retry(function() { return rp('http://localhost:8000').promise() }, { max_tries: 5 })
    .then(function (res) {
        console.log('success');
    })
    .catch(function (err) {
        console.log('fail');
    });
```

The way you wrote it would only call request-promise once in the global context which returns the single promise that's then passed into bluebird-retry, but there's nothing to actually retry, hence it only issues the request once.
